msb-wifi:    # configuration of the wifi service
  verbose : false
  print_stdout : false
  targets:
    base_station:
      target_address : "base-04-a.local"
      target_port    : 9870
#    san_laptop:
#      target_address : "192.168.2.10"
#      target_port    : 9870
    flucto_server:
      target_address : "flucto.tech"
      target_port    : 9870


