protocol : "tcp"  # ipc protocol
interface: "127.0.0.1"  # the interface to bind to
publisher_port: int = 5555  # port used by primary producers
subscriber_port: int = 5556  # port used by primary consumers



