verbose : false
print_stdout : false
data_dir : "/home/msb/msb_data"
filename_datetime_fmt : "%Y%m%dT%H%M%S%z"
logfile_interval : 3600  # temporal length in seconds of each logfile: 1h (3600s)
key_order:
    att : ["datetime", "epoch", "uptime", "roll", "roll_corr", "pitch", "pitch_corr"]
    imu : ["datetime", "epoch", "uptime", "acc_x", "acc_y", "acc_z", "rot_x", "rot_y", "rot_z", "mag_x", "mag_y", "mag_z", "temp"]
    gps : ["datetime", "epoch", "uptime", "mode", "time", "lat", "lon", "altHAE", "altMSL", "magvar"]
    opt : ["datetime", "epoch", "uptime", "velocity"]
