verbose : false
print_stdout : false
data_dir : "/home/msb/msb_data"
filename_datetime_fmt : "%Y%m%dT%H%M%S%z"
logfile_interval : 3600  # temporal length in seconds of each logfile: 1h (3600s)
key_order:
    att : ["epoch", "uptime", "roll", "roll_corr", "pitch", "pitch_corr", "datetime"]
    imu : ["epoch", "uptime", "acc_x", "acc_y", "acc_z", "rot_x", "rot_y", "rot_z", "mag_x", "mag_y", "mag_z", "temp", "datetime"]
    gps : ["epoch", "uptime", "mode", "time", "latitude", "longitude", "altitude", "altitude_msl", "track", "mag_track", "mag_var", "speed", "datetime"]
    pwr : ["epoch", "uptime", "load-1", "load-5", "load-15", "mem-available", "swap-cached", "datetime"]
