verbose : false     # print debugging information
print_stdout : false     # print data to stdout
topic : opt
width : 1920
height : 1080
fps : 10
max_tracks : 10
show_video : false
show_roi : false
video_source : picamera3
px_to_m : 1
rotate : 
    center : [960, 540]
    angle : 0
    scale : 1
roi : 
    xmin : 100
    xmax : 1820
    ymin : 100
    ymax : 980
        




